#cloud-config
hostname: unc-k8s-cp-2
manage_etc_hosts: true
chpasswd:
  expire: False
users:
  - default
  - name: cloudinit
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    # mkpasswd --method=SHA-512 --rounds=4096
    # password is zaq12wsx
    passwd: $6$rounds=4096$Xlyxul70asLm$9tKm.0po4ZE7vgqc.grptZzUU9906z/.vjwcqz/WYVtTwc5i2DWfjVpXb8HBtoVfvSY61rvrs/iwHxREKl3f20
package_upgrade: true
runcmd:
  - su - root -c "curl -s https://raw.githubusercontent.com/unchama/kude-cluster-on-proxmox/main/scripts/k8s-cp-setup.sh > /opt/k8s-cp-setup.sh"
  - su - root -c "/bin/bash -eu /opt/k8s-cp-setup.sh k8s-cp-2"
