apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-51.2.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.2.0
    helm:
      releaseName: prometheus
      skipCrds: true
      values: |
        defaultRules:
          create: true
          rules:
            kubeProxy: false
            alertmanager: false
        grafana:
          defaultDashboardsTimezone: Asia/Tokyo
          plugins:
            - grafana-piechart-panel
          grafana.ini:
            server:
              domain: localhost
              root_url: '%(protocol)s://%(domain)s:%(http_port)s'
              enforce_domain: false
            log:
              level: warn
            date_formats:
              default_timezone: Asia/Tokyo
            security:
              cookie_secure: false
              strict_transport_security: true
              content_security_policy: true
          deploymentStrategy:
            type: Recreate
          persistence:
            enabled: true
            size: 10Gi
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 50Gi
            resources:
              requests:
                memory: 2Gi
            retention: 60d
        alertmanager:
          enabled: false
        kubeProxy:
          enabled: false
        kubeEtcd:
          endpoints:
            - 172.16.17.11
            - 172.16.17.12
            - 172.16.17.13
          service:
            enabled: true
            port: 2381
            targetPort: 2381
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
