apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/Chart.yaml#L6
    targetRevision: 4.0.3
    helm:
      releaseName: velero
      # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
      values: |
        metrics:
          serviceMonitor:
            enabled: true
        cleanUpCRDs: true
        configuration:
          backupStorageLocation:
          - name: default
            provider: aws
            accessMode: ReadWrite
            credential:
              name: velero-for-minio-access-credential
              key: cloud
            config:
              region: minio 
              s3ForcePathStyle: true
              s3Url: http://minio.velero-for-minio.svc:9000
        credentials:
          useSecret: true
          name: velero-for-minio-access-credential
          secretContents:
            cloud: |
              [default]
              aws_access_key_id = iamrootuser
              aws_secret_access_key = t0p-Secret
        schedules:
          mybackup:
            schedule: "0 0 * * *"
            template:
              ttl: "240h"
              storageLocation: default
              includedNamespaces:
              - mc-test
  destination:
    server: https://kubernetes.default.svc
    namespace: backup
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
