apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/unchama/kube-cluster-on-proxmox
        revision: main
        directories:
          - path: k8s-manifests/apps/cluster-wide-apps/*
  template:
    metadata:
      # 各Application が argocd namespace に配置されるため prefix した方が安全
      name: "cluster-wide-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cluster-wide-apps
      source:
        repoURL: https://github.com/unchama/kube-cluster-on-proxmox
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'cluster-wide-apps'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
# See the following file for documentations
# https://github.com/argoproj/argo-cd/blob/a6c664b2aefc513936e9f56c1a373bdbddcd5727/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-app-resources
  namespace: argocd
spec:
  project: argocd-root
  source:
    repoURL: https://github.com/unchama/kube-cluster-on-proxmox
    targetRevision: main
    path: k8s-manifests/apps/cluster-wide-app-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cluster-wide-apps'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mc-test-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/unchama/kube-cluster-on-proxmox
        revision: main
        directories:
          - path: k8s-manifests/apps/mc-test/*
  template:
    metadata:
      # 各Application が argocd namespace に配置されるため prefix した方が安全
      name: "mc-test-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: mc-test
      source:
        repoURL: https://github.com/unchama/kube-cluster-on-proxmox
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: mc-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
