---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.10/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.10/manifests/metallb.yaml
  - metallb-cm.yaml
