apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-lb
spec:
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  type: LoadBalancer
  loadBalancerIP: 172.16.3.130
