apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: hourly
spec:
  claimSelector:
    matchLabels:
      "snapschedule/hourly": "enabled"
  retention:
    maxCount: 24
  schedule: "*/10 * * * *"
