# Config values for the ArgoCD Helm Chart.
# For default values, see
# https://github.com/argoproj/argo-helm/blob/07d63255ae19ff1e08a22e71c932f686f8f619ac/charts/argo-cd/values.yaml
server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    # -- Average CPU utilization percentage (to the requested resource) for the Argo CD server [HPA]
    targetCPUUtilizationPercentage: 90
    # -- Average memory utilization percentage (to the requested resource) for the Argo CD server [HPA]
    targetMemoryUtilizationPercentage: 175
  resources:
    requests:
      cpu: 100m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 128Mi
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 0

  configEnabled: true
  # -- [General Argo CD configuration]
  config:
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance
    kustomize.buildOptions: --load-restrictor LoadRestrictionsNone

controller:
  enableStatefulSet: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 0

dex:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 0

redis:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  replicaCount: 1
  resources:
    limits:
      cpu: 1500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 128Mi

applicationSet:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

notifications:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi
