- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: cloudinit
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" } 
  notify:
    - restart sshd
